app/project/models.py
from app.extensions.database import db
from datetime import datetime

class Author(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150))
    street = db.Column(db.String(150))
    city = db.Column(db.String(150))
    state = db.Column(db.String(150))
    zip = db.Column(db.String(10))
    country = db.Column(db.String(80))
    initiative = db.relationship('Initiative', backref='author', uselist=False, lazy=True)

class Initiative(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150), unique=True)
    description = db.Column(db.String(200))
    owner = db.Column(db.String(80))
    tag = db.Column(db.String(80))
    picture_url = db.Column(db.String(200))
    author_id = db.Column(db.Integer, db.ForeignKey('author.id'))
    

app/sierra_b/models.py
from app.extensions.database import db

class Project(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(150), unique=True)
    description = db.Column(db.String(200))
    owner = db.Column(db.String(80))
    tag = db.Column(db.String(80))
    picture_url = db.column(db.String(200))

    def __init__(self, title, description, picture_url, owner=None, tag=None):
        self.title = title
        self.description = description
        self.owner = owner
        self.tag = tag
        self.picture_url = picture_url

app/__init__.py
from flask import Flask, redirect, url_for, render_template, send_file
from dotenv import load_dotenv
from app.extensions.database import db, migrate
from app.project.models import Author, Initiative
import os
from . import sierra_b

def create_app():
    app = Flask(__name__)

    load_dotenv()

    app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    register_extensions(app)
    register_blueprints(app)
    return app

def register_blueprints(app: Flask):
    app.register_blueprint(sierra_b.routes.bleuprint)

def register_extensions(app: Flask):
    db.init_app(app)
    migrate.init_app(app, db, compare_type=True)

app/project/__init__.py
from . import models

app/sierra_b/__init__.py
from .import routes, models

app/sierra_b/routes.py
from flask import Blueprint, render_template
from .models import Project

bleuprint = Blueprint('sierra_b', __name__)


pro_jects = {
    '001': 'TP_Smart',
    '002': 'Shag_4_CheaP',
    '003': 'Wi_GarDen',
    '005': 'iN_iT'
}

# Home Route
@bleuprint.route('/')
def index():
    return render_template('index.html')

# Project Page route
@bleuprint.route('/projects')
def projects():
    return render_template('our-projects.html', project=pro_jects)


# About Us Page route
@bleuprint.route('/about-us')
def about():
    return render_template('about-us.html')

# Investor Page Route
@bleuprint.route('/investors')
def investor():
    return render_template('investor-page.html')

# Entrepreneur Page route
@bleuprint.route('/entrepreneur')
def entrepreneur():
    return render_template('ent-page.html')

# contact page route
@bleuprint.route('/contact')
def contact():
    return render_template('contact.html')

@bleuprint.route('/legal')
def legal():
    return render_template('/legal.html')

app/templates/about-us.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width initial-scale=1.0">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300|7CCinzel+Decorative:700">
        <meta name="author" content="Thomas Smart">
        <title>About Sierra Bloom</title>
    </head>

    <body>
        <header>
            <h1>Sorry! We are under construction. Check in 3 weeks</h1>
            <button type="submit" class="cta-button back-homepage"><a href="{{url_for('sierra_b.index')}}" style="text-decoration: none;">Back</a></button>
        </header>
    </body>
</html>

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale = 1.0">
        <meta name="author" content="Thomas Smart">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300|7CCinzel+Decorative:700">
        <link rel="stylesheet" href="{{url_for('static', filename='styles/styles.css')}}">
        <title>Base</title>
    </head>
    <body>
        <header class="header-content">
            <h1>Sierra Bloom</h1>
            <p>Unlocking Investment Opportunities</p>
            <!--Navigation Menu-->
            <div class="nav-container">
                <nav class="main-navigation">
                    <ul>
                        <li><a href="{{url_for('index')}}" style="text-decoration: none;">Home</a></li>
                        <li><a href="{{url_for('about')}}">About Us</a></li>
                        <li><a href="{{url_for('projects')}}">Our Projects</a></li>
                        <li><a href="{{url_for('investor')}}">Investors</a></li>
                        <li><a href="{{url_for('entrepreneur')}}">Entrepreneurs</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </nav>
            </div>
        </header>
        <div class="page-container">
            <main class="main-content">
            
            </main>
        </div>
        <!--Footer Section-->
        <section>
            <footer class="footer-section">
                <div class="footer-text">
                    <p style="font-size: 14px;"> 2024 SierraBloom. All Rights Reserved</p>
                    <a href="#" style="font-size: 14px;">Privacy Policy</a>
                    <a href="#" style="font-size: 14px;">Terms Of Service</a>
                </div>
                <div class="footer-socials">
                    <a href="https://www.linkedin.com/company/sierrabloom/?viewAsMember=true">Linkedin</a>
                    <a href="#">Faceook</a>
                    <a href="#">Twitter</a>
                </div>
            </footer>
        </section>
        <script src="{{ url_for('static', filename='scripts/script.js') }}"></script>
    </body>
</html>

app/templates/contact.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width initial-scale=1.0">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300|7CCinzel+Decorative:700">
        <meta name="author" content="Thomas Smart">
        <title>About Sierra Bloom</title>
    </head>

    <body>
        <header>
            <h1><b>COMING SOON!!</b></h1>
            <button type="submit" class="cta-button back-homepage"><a href="{{url_for('sierra_b.index')}}" style="text-decoration: none;">Back</a></button>
        </header>
    </body>
</html>

app/templates/ent-page.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width initial-scale=1.0">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300|7CCinzel+Decorative:700">
        <meta name="author" content="Thomas Smart">
        <title>Submit Your Idea</title>
    </head>

    <body>
        <header>
            <h1>Sorry! We are under construction. Check in 3 weeks</h1>
            <button type="submit" class="cta-button back-homepage"><a href="sierra_b.index.html" style="text-decoration: none;">Back</a></button>
        </header>
    </body>
</html>

app/templates/faulty_extend_index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<section class="gallery-placeholder">
    <div class="gallery-slider">
        <div class="gallery-slide">
            <img src="{{ url_for('static', filename='images/sierra5.jpeg') }}" alt="#">
        </div>
        <div class="gallery-slide">
            <img src="{{ url_for('static', filename='images/sierra2.avif') }}" alt="#">
        </div>
        <div class="gallery-slide">
            <img src="{{ url_for('static', filename='images/Sierra3.webp') }}" alt="#">
        </div>
        <div class="gallery-slide">
            <img src="{{ url_for('static', filename='images/sierra-5.jpg') }}" alt="#">
        </div>
    </div>
</section>

<!--About Section-->
<section class="about-section">
    <h2>About Us</h2>
    <p class="about-us-text">
        At SierraBloom, our mission is to showcase the wealth of investment opportunities available in Sierra Leone. 
        We are dedicated to bridging the gap between global investors and the emerging market potential in this vibrant region.
    </p>
    <div class="about-content">
        <div class="box vision-text">
            <h3>Our Vision</h3>
            <p>SierraBloom is a platform dedicated to showing the rich investment opportunities present in Sierra Leone</p>
        </div>
        <div class="box mission-text">
            <h3>Our Mission</h3>
            <p>We aim to facilitate economic growth by connecting global investors with promising sectors in the region</p>
        </div>
    </div>
</section>

<!--Why Sierra Leone Section-->
<section class="why-section">
    <div class="why-section-content">
        <h2>Why Sierra Leone?</h2>
        <p>Discover why Sierra Leone is an Attractive Destination For Investors</p>
        <div>
            <ul class="stat-list"> 
                <li class="why-section-stable-growth">
                    <img src="#" alt="">
                    <a href="#">Stable growth</a>
                </li>
                <li class="why-section-natural-resources">
                    <img src="#" alt="">
                    <a href="#">Rich Natural Resources</a>
                </li>
                <li class="why-section-strategic-location">
                    <img src="#" alt="">
                    <a href="#">Strategic Location</a>
                </li>
                <li class="why-section-investment-friendly-policies">
                    <img src="#" alt="">
                    <a href="#">Investment-Friendly Policies</a>
                </li>
            </ul>
        </div>
    </div>
</section>

<!--sectors we focus on-->
<section class="sectors-section">
    <h2>Sectors We Focus On</h2>
    <div class="accordion">
        <div class="accordion-header">+ Agriculture</div>
        <div class="accordion-content">
            Focus on innovative farming techniques and sustainable practices
        </div>
        <div class="accordion-header">+ Mining</div>
        <div class="accordion-content">
            Committed to sustainable practices in resource extraction and community engagement.
        </div>
        <div class="accordion-header">+ Tourism</div>
        <div class="accordion-content">
            Promoting eco-friendly travel experiences and cultural preservation.
        </div>
        <div class="accordion-header">+ Energy</div>
        <div class="accordion-content">
            Advancing renewable energy solutions for a sustainable future.
        </div>
        <div class="accordion-header">+ Infrastructure</div>
        <div class="accordion-content">
            Building resilient and modern infrastructure for communities.
        </div>
    </div>
</section>

<!--contact us / newsletter sign up section-->
<section id="contact" class="contact-section">
    <h2>Stay Updated</h2>
    <p>Sign up to stay updated with different investment opportunities in Sierra Leone.</p>
    <button type="submit" class="cta-button entrepreneur-button"><a href="#">Applicants</a></button>
    <button type="submit" class="cta-button investor-button"><a href="#">Investors</a></button>
</section>

{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale = 1.0">
        <meta name="author" content="Thomas Smart">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300|7CCinzel+Decorative:700">
        <link rel="stylesheet" href="static/styles/styles.css">
        <title>Home</title>
    </head>
    <body> 
        <header class="header-content">
            <h1>Sierra Bloom</h1>
            <p>Unlocking Investment Opportunities</p>
            <!--Navigation Menu-->
            <div class="nav-container">
                <nav class="main-navigation">
                    <ul>
                        <li><a href="{{url_for('sierra_b.index')}}" style="text-decoration: none;">Home</a></li>
                        <li><a href="{{url_for('sierra_b.about')}}">About Us</a></li>
                        <li><a href="{{url_for('sierra_b.projects')}}">Our Projects</a></li>
                        <li><a href="{{url_for('sierra_b.investor')}}">Investors</a></li>
                        <li><a href="{{url_for('sierra_b.entrepreneur')}}">Entrepreneurs</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="{{url_for('sierra_b.legal')}}">Privacy</a></li>
                    </ul>
                </nav>
            </div>
        </header>
        <div class="page-container">
            <main class="main-content">
                <section class="gallery-placeholder">
                    <div class="gallery-slider">
                        <div class="gallery-slide">
                            <img src="{{url_for('static', filename='images/sierra5.jpeg')}}" alt="#">
                        </div>
                        <div class="gallery-slide">
                            <img src="{{url_for('static', filename='images/sierra2.avif')}}" alt="#">
                        </div>
                        <div class="gallery-slide">
                            <img src="{{url_for('static', filename='images/Sierra3.webp')}}" alt="#">
                        </div>
                        <div class="gallery-slide">
                            <img src="{{url_for('static', filename='images/sierra-5.jpg')}}" alt="#">
                        </div>
                    </div>
                </section>

                <!--About Section-->
                <section class="about-section">
                    <h2>About Us</h2>
                    <p class="about-us-text">
                        At SierraBloom, our mission is to showcase the wealth of investment opportunities available in Sierra Leone. 
                        We are dedicated to bridging the gap between global investors and the emerging market potential in this vibrant region.
                    </p>
                    <div class="about-content">
                        <div class="box vision-text">
                            <h3>Our Vision</h3>
                            <p>SierraBloom is a platform dedicated to showing the rich investment opportunities present in Sierra Leone</p>
                        </div>
                        <div class="box mission-text">
                            <h3>Our Mission</h3>
                            <p>We aim to facilitate economic growth by connecting global investors with promising sector in the region</p>
                        </div>
                    </div>
                </section>
                <!--Why Sierra Leone Section-->
                <section class="why-section">
                    <div class="why-section-content">
                        <h2>Why Sierra Leone?</h2>
                        <p>Discover why Sierra Leone is an Attractive Destination For Investors</p>
                        <div>
                            <ul class="stat-list"> 
                                <li class="why-section-stable-growth">
                                    <img src="#" alt="">
                                    <a href="#">Stable growth</a>
                                </li>
                                <li class="why-section-natural-resources">
                                    <img src="#" alt="">
                                    <a href="#">Rich Natural Resources</a>
                                </li>
                                <li class="why-section-strategic-location">
                                    <img src="#" alt="">
                                    <a href="#">Strategic Location</a>
                                </li>
                                <li class="why-section-investment-friendly-policies">
                                    <img src="#" alt="">
                                    <a href="#">Investment-Friendly Policies</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </section>
                <!--sectiors we focus on-->
                <section class="sectors-section">
                    <h2>Sectors We Focus On</h2>
                    <div class="accordion">
                        <div class="accordion-header">+ Agriculture</div>
                        <div class="accordion-content">
                            Focus on innovative farming techniques and sustainable practices
                        </div>
                        <div class="accordion-header">+ Mining</div>
                        <div class="accordion-content">
                            Committed to sustainable practices in resource extraction and community engagement.
                        </div>
                        <div class="accordion-header">+ Tourism</div>
                        <div class="accordion-content">
                        Promoting eco-friendly travel experiences and cultural preservation.
                        </div>
                        <div class="accordion-header">+ Energy</div>
                        <div class="accordion-content">
                            Advancing renewable energy solutions for a sustainable future.
                        </div>
                        <div class="accordion-header">+ Infrastructure</div>
                        <div class="accordion-content">
                            Building resilient and modern infrastructure for communities.
                        </div>
                    </div>
                </section>
                <!--contact us / newsletter sign up section-->
                <section id="contact" class="contact-section">
                    <h2>Stay Updated</h2>
                    <p>Sign up to stay updated with different investment opportunities in Sierra Leone.</p>
                    <button type="submit" class="cta-button entrepreneur-button"><a href="#">Applicants</a></button>
                    <button type="submit" class="cta-button investor-button"><a href="#">Investors</a></button>
                </section>
            </main>
        </div>
        <!--Footer Section-->
        <section>
            <footer class="footer-section">
                <div class="footer-text">
                    <p style="font-size: 14px;"> 2024 SierraBloom. All Rights Reserved</p>
                    <a href="#" style="font-size: 14px;">Privacy Policy</a>
                    <a href="#" style="font-size: 14px;">Terms Of Service</a>
                </div>
                <div class="footer-socials">
                    <a href="https://www.linkedin.com/company/sierrabloom/?viewAsMember=true">Linkedin</a>
                    <a href="#">Faceook</a>
                    <a href="#">Twitter</a>
                </div>
            </footer>
        </section>
        <script src="{{ url_for('static', filename='scripts/script.js') }}"></script>
    </body>
</html>

app/templates/investor-page.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width initial-scale=1.0">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300|7CCinzel+Decorative:700">
        <meta name="author" content="Thomas Smart">
        <title>Invest In Sierra Leone</title>
    </head>

    <body>
        <header>
            <h1>Sorry! We are under construction. Check in 3 weeks</h1>
            <button type="submit" class="cta-button back-homepage"><a href="{{url_for('sierra_b.index')}}" style="text-decoration: none;">Back</a></button>
        </header>
    </body>
</html>

app/templates/our-projects.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width initial-scale=1.0">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300|7CCinzel+Decorative:700">
        <meta name="author" content="Thomas Smart">
        <title>Projects</title>
    </head>

    <body>
        <header>
            <h1>Our Projects</h1>
            <ul>
                {% for key, value in project.items() %}
                    {% if key == '003' %}
                        <s>{{ value }}</s>
                    {% else %}
                        <li>
                            <a href="{{ url_for('sierra_b.investor') }}" style="text-decoration: none;">{{ value }}</a><br>
                            <button type="submit" class="cta-button download_pitch_deck">Pitch Deck</button>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
            
            <button type="submit" class="cta-button back-homepage"><a href="{{url_for('sierra_b.index')}}" style="text-decoration: none;">Back</a></button>
        </header>
    </body>
</html>

app/templates/smart1.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale = 1.0">
        <meta name="author" content="Thomas Smart">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300|7CCinzel+Decorative:700">
        <link rel="stylesheet" href="static/styles/styles.css">
        <title>Home</title>
    </head>
    <body>
        <header class="header-content">
            <h1>Sierra Bloom</h1>
            <p>Unlocking Investment Opportunities</p>
            <!--Navigation Menu-->
            <div class="nav-container">
                <nav class="main-navigation">
                    <ul>
                        <li><a href="{{url_for('index')}}" style="text-decoration: none;">Home</a></li>
                        <li><a href="{{url_for('about')}}">About Us</a></li>
                        <li><a href="{{url_for('projects')}}">Our Projects</a></li>
                        <li><a href="{{url_for('investor')}}">Investors</a></li>
                        <li><a href="{{url_for('entrepreneur')}}">Entrepreneurs</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </nav>
            </div>
        </header>
        <div class="page-container">
            <main class="main-content">
                <section class="gallery-placeholder">
                    <div class="gallery-slider">
                        <div class="gallery-slide">
                            <img src="{{url_for('static', filename='images/sierra5.jpeg')}}" alt="#">
                        </div>
                        <div class="gallery-slide">
                            <img src="{{url_for('static', filename='images/sierra2.avif')}}" alt="#">
                        </div>
                        <div class="gallery-slide">
                            <img src="{{url_for('static', filename='images/Sierra3.webp')}}" alt="#">
                        </div>
                        <div class="gallery-slide">
                            <img src="{{url_for('static', filename='images/sierra-5.jpg')}}" alt="#">
                        </div>
                    </div>
                </section>

                <!--About Section-->
                <section class="about-section">
                    <h2>About Us</h2>
                    <p class="about-us-text">
                        At SierraBloom, our mission is to showcase the wealth of investment opportunities available in Sierra Leone. 
                        We are dedicated to bridging the gap between global investors and the emerging market potential in this vibrant region.
                    </p>
                    <div class="about-content">
                        <div class="box vision-text">
                            <h3>Our Vision</h3>
                            <p>SierraBloom is a platform dedicated to showing the rich investment opportunities present in Sierra Leone</p>
                        </div>
                        <div class="box mission-text">
                            <h3>Our Mission</h3>
                            <p>We aim to facilitate economic growth by connecting global investors with promising sector in the region</p>
                        </div>
                    </div>
                </section>
                <!--Why Sierra Leone Section-->
                <section class="why-section">
                    <div class="why-section-content">
                        <h2>Why Sierra Leone?</h2>
                        <p>Discover why Sierra Leone is an Attractive Destination For Investors</p>
                        <div>
                            <ul class="stat-list"> 
                                <li class="why-section-stable-growth">
                                    <img src="#" alt="">
                                    <a href="#">Stable growth</a>
                                </li>
                                <li class="why-section-natural-resources">
                                    <img src="#" alt="">
                                    <a href="#">Rich Natural Resources</a>
                                </li>
                                <li class="why-section-strategic-location">
                                    <img src="#" alt="">
                                    <a href="#">Strategic Location</a>
                                </li>
                                <li class="why-section-investment-friendly-policies">
                                    <img src="#" alt="">
                                    <a href="#">Investment-Friendly Policies</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </section>
                <!--sectiors we focus on-->
                <section class="sectors-section">
                    <h2>Sectors We Focus On</h2>
                    <div class="accordion">
                        <div class="accordion-header">+ Agriculture</div>
                        <div class="accordion-content">
                            Focus on innovative farming techniques and sustainable practices
                        </div>
                        <div class="accordion-header">+ Mining</div>
                        <div class="accordion-content">
                            Committed to sustainable practices in resource extraction and community engagement.
                        </div>
                        <div class="accordion-header">+ Tourism</div>
                        <div class="accordion-content">
                        Promoting eco-friendly travel experiences and cultural preservation.
                        </div>
                        <div class="accordion-header">+ Energy</div>
                        <div class="accordion-content">
                            Advancing renewable energy solutions for a sustainable future.
                        </div>
                        <div class="accordion-header">+ Infrastructure</div>
                        <div class="accordion-content">
                            Building resilient and modern infrastructure for communities.
                        </div>
                    </div>
                </section>
                <!--contact us / newsletter sign up section-->
                <section id="contact" class="contact-section">
                    <h2>Stay Updated</h2>
                    <p>Sign up to stay updated with different investment opportunities in Sierra Leone.</p>
                    <button type="submit" class="cta-button entrepreneur-button"><a href="#">Applicants</a></button>
                    <button type="submit" class="cta-button investor-button"><a href="#">Investors</a></button>
                </section>
            </main>
        </div>
        <!--Footer Section-->
        <section>
            <footer class="footer-section">
                <div class="footer-text">
                    <p style="font-size: 14px;"> 2024 SierraBloom. All Rights Reserved</p>
                    <a href="#" style="font-size: 14px;">Privacy Policy</a>
                    <a href="#" style="font-size: 14px;">Terms Of Service</a>
                </div>
                <div class="footer-socials">
                    <a href="https://www.linkedin.com/company/sierrabloom/?viewAsMember=true">Linkedin</a>
                    <a href="#">Faceook</a>
                    <a href="#">Twitter</a>
                </div>
            </footer>
        </section>
        <script src="{{ url_for('static', filename='scripts/script.js') }}"></script>
    </body>
</html>

templates/about-us.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width initial-scale=1.0">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300|7CCinzel+Decorative:700">
        <meta name="author" content="Thomas Smart">
        <title>About Sierra Bloom</title>
    </head>

    <body>
        <header>
            <h1>Sorry! We are under construction. Check in 3 weeks</h1>
            <button type="submit" class="cta-button back-homepage"><a href="index.html" style="text-decoration: none;">Back</a></button>
        </header>
    </body>
</html>